hackathon/urls.py
from django.contrib import admin
from django.urls import path, include
from hackme.urls import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hackme.urls')),
]

hackme/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.main,name='main'),
    path('form', views.form, name='form'),
    path('form1', views.form1, name='form1'),
    path('detail/<details>', views.detail, name='detail'),
    path('contact', views.contact, name='contact'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hackme/models.py
from django.db import models
from django.contrib import admin

class Register(models.Model):
	#id_1=models.UUIDField(default=uuid.uuid4, editable=True)
	CHOICES=(
		(1,'1'),
		(2,'2'),
		(3,'3'),
		)
	teamName=models.CharField(primary_key=True,max_length=100, null=False, blank=False)
	emailAddress=models.EmailField(null=False)
	github_username=models.CharField(max_length=150, null=False, blank=False)
	project_repo_name=models.CharField(max_length=150, null=False, blank=False)
	teamSize=models.IntegerField(choices=CHOICES)
	userDetail1=models.CharField(max_length=150, null=False, blank=False)
	userDetail2=models.CharField(max_length=150,blank=True,null=True)
	userDetail3=models.CharField(max_length=150,blank=True,null=True)
	fieldProject=models.CharField(max_length=30,null=False, blank=False)
	title=models.CharField(max_length=50,null=False, blank=False)
	synopsis=models.TextField(null=False, blank=False)

hackme/forms.py
from .models import Register
from django import forms

class RegistrationForm(forms.ModelForm):
	class Meta:
		model = Register
		fields = ['teamName', 'emailAddress', 'github_username', 'project_repo_name', 'teamSize', 'userDetail1', 'userDetail2', 'userDetail3','fieldProject', 'title', 'synopsis']

hackme/views.py
from django.shortcuts import render
from .models import *
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import RegistrationForm
from django.utils import timezone
from django.db.models import Q

def main(request):
	return render(request, 'hackme/main2.html')


def form(request):
	return render(request, 'hackme/formBackground.html')

def form1(request):
	if(request.method=='POST'):
		print(request)
		form=RegistrationForm(request.POST)
		if(form.is_valid()):
			form.save()

			team=request.POST.get('teamName')
			return render(request, 'hackme/cform.html', {'detail':team})

	else:
		form=RegistrationForm()
	return render(request, 'hackme/cform.html', {'form':form})

def contact(request):
	if(request.method=='POST'):

		form=ContactForm(request.POST)
		if(form.is_valid()):
			form.save()
			return HttpResponseRedirect('/contact')
	else:
		form=ContactForm()
	return render(request, 'hackme/cform.html', {'form':form})


def detail(request, details):
	teamdetails=Register.objects.filter(Q(teamName=details))
	timer=timezone.now()
	f=str(timer).split(" ")
	time=f[1]
	time=str(time).split(":")
	h=str(((int)(time[0])))
	m=str(((int)(time[1])))
	
	return render(request, 'hackme/detail.html', {'timer':h+":"+m+":"+time[2].split(".")[0], 'teamName':teamdetails})

hackme/templates/hackme/cform.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head>
</SCRIPT>
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style type="text/css">
.loader {
   border: 16px solid #f3f3f3;
   border-radius: 50%;
   border-top: 16px solid blue;
   border-bottom: 16px solid blue;
   width: 120px;
   height: 120px;
   -webkit-animation: spin 2s linear infinite;
   animation: spin 2s linear infinite;
}
.container .btn {
   position: relative;
   top: 50%;
   left: 35%;
   border: none;
   color: black;
   padding: 15px 32px;
   text-align: center;
   text-decoration: none;
   display: inline-block;
   font-size: 16px;
   margin: 4px 2px;
   cursor: pointer;
}
.container .btn:hover {
   background-color: black;
   color: white;
}
</style>
<title>Contact</title>
</head>
<body>
   <form method="POST" action="">
      {% csrf_token %}
      <br>
      <div class="container-fluid">
         <div class="container">
            <b>
               {% for non_field_error in form.non_field_errors %}
               <p class="help is-danger">{{ non_field_error }}</p>
               {% endfor %}
               <div id="div_id_teamName" class="form-group">
                  <label for="id_teamName" class="control-label  requiredField">
                     Team Name<span class="asteriskField">*</span> </label> 
                     <div class="controls ">
                        <input type="text" name="teamName" maxlength="100" class="textinput textInput form-control" required="" id="id_teamName" placeholder="Your Team's Name"> 
                        {% for error in form.teamName.errors %}
                        <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                     </div>
                  </div>
                  <div id="div_id_emailAddress" class="form-group">
                     <label for="id_emailAddress" class="control-label  requiredField">
                        Email Address<span class="asteriskField">*</span> </label> 
                        <div class="controls ">
                           <input type="email" name="emailAddress" placeholder="Email Address" maxlength="254" class="emailinput form-control" required="" id="id_emailAddress">
                           {% for error in field.errors %}
                           <p class="help is-danger">{{ error }}</p>
                           {% endfor %} 
                        </div>
                     </div>
                     <div id="div_id_github_username" class="form-group">
                        <label for="id_github_username" class="control-label  requiredField">
                           Github Link<span class="asteriskField">*</span> </label> 
                           <div class="controls ">
                              <input type="text" name="github_username" placeholder="https://github.com/abhinavsharma629" maxlength="150" class="textinput textInput form-control" required="" id="id_github_username">
                              {% for error in field.errors %}
                              <p class="help is-danger">{{ error }}</p>
                              {% endfor %}  
                           </div>
                        </div>
                        <div id="div_id_project_repo_name" class="form-group">
                           <label for="id_project_repo_name" class="control-label  requiredField">
                              Project Repository Link<span class="asteriskField">*</span> </label> 
                              <div class="controls ">
                                 <input type="text" placeholder="https://github.com/abhinavsharma629/Data-Structures" name="project_repo_name" maxlength="150" class="textinput textInput form-control" required="" id="id_project_repo_name">
                                 {% for error in field.errors %}
                                 <p class="help is-danger">{{ error }}</p>
                                 {% endfor %}   
                              </div>
                           </div>
                           <div id="div_id_teamSize" class="form-group">
                              <label for="id_teamSize" class="control-label  requiredField">
                                 Team Size<span class="asteriskField">*</span> </label> 
                                 <div class="controls ">

                                    <select name="teamSize" class="select form-control" required="" id="id_teamSize" onchange="myfunction(this)">
                                       <option value="1" selected>1</option>
                                       <option value="2">2</option>
                                       <option value="3">3</option>
                                    </select>
                                    {% for error in form.teamSize.errors %}
                                    <p class="help is-danger">{{ error }}</p>
                                    {% endfor %}
                                 </div>
                              </div>
                              <div id="div_id_userDetail1" class="form-group">
                                 <label for="id_userDetail1" class="control-label  requiredField">
                                    User 1<span class="asteriskField">*</span> </label> 
                                    <div class="controls ">
                                       <input type="text" name="userDetail1" placeholder="User Detail:- Name, Enrollment Number, Shirt Size" maxlength="150" class="textinput textInput form-control" required="" id="id_userDetail1">
                                       {% for error in form.userDetail1.errors %}
                                       <p class="help is-danger">{{ error }}</p>
                                       {% endfor %} 
                                    </div>
                                 </div>
                                 <div id="div_id_userDetail2" class="form-group" style="display: none;">
                                    <label for="id_userDetail2" class="control-label ">
                                       User 2<span class="asteriskField">*</span>
                                    </label> 
                                    <div class="controls ">
                                       <input type="text" placeholder="User Detail:- Name, Enrollment Number, Shirt Size" name="userDetail2" maxlength="150" class="textinput textInput form-control" id="id_userDetail2" required=""> 
                                       {% for error in form.userDetail2.errors %}
                                       <p class="help is-danger">{{ error }}</p>
                                       {% endfor %}
                                    </div>
                                 </div>
                                 <div id="div_id_userDetail3" class="form-group" style="display: none;">
                                    <label for="id_userDetail3" class="control-label ">
                                       User 3<span class="asteriskField">*</span>
                                    </label> 
                                    <div class="controls ">
                                       <input type="text" placeholder="User Detail:- Name, Enrollment Number, Shirt Size" name="userDetail3" maxlength="150" class="textinput textInput form-control" id="id_userDetail3" required="">
                                       {% for error in form.userDetail3.errors %}
                                       <p class="help is-danger">{{ error }}</p>
                                       {% endfor %}
                                    </div>
                                 </div>
                                 <div id="div_id_fieldProject" class="form-group">
                                    <label for="id_fieldProject" class="control-label  requiredField">
                                       Project Field<span class="asteriskField">*</span> </label> 
                                       <div class="controls ">
                                          <input type="text" name="fieldProject" placeholder="Example:- AI" maxlength="30" class="textinput textInput form-control" required="" id="id_fieldProject"> 
                                          {% for error in form.fieldProject.errors %}
                                          <p class="help is-danger">{{ error }}</p>
                                          {% endfor %}
                                       </div>
                                    </div>
                                    <div id="div_id_title" class="form-group">
                                       <label for="id_title" class="control-label  requiredField">
                                          Title<span class="asteriskField">*</span> </label> 
                                          <div class="controls ">
                                             <input type="text" name="title" placeholder="Example:- StopStalk" maxlength="50" class="textinput textInput form-control" required="" id="id_title"> 
                                             {% for error in form.title.errors %}
                                             <p class="help is-danger">{{ error }}</p>
                                             {% endfor %}
                                          </div>
                                       </div>
                                       <div id="div_id_synopsis" class="form-group">
                                          <label for="id_synopsis" class="control-label  requiredField">
                                             Synopsis<span class="asteriskField">*</span> </label> 
                                             <div class="controls ">
                                                <textarea name="synopsis" placeholder="Maximum:- 500 words" cols="40" rows="10" class="textarea form-control" required="" id="id_synopsis"></textarea>
                                                {% for error in form.synopsis.errors %}
                                                <p class="help is-danger">{{ error }}</p>
                                                {% endfor %}
                                             </div>
                                          </div>
                                          <button class="btn">
                                             Register
                                          </button>
                                       </b>
                                    </div>
                                 </div>
                              </form>
                              <script type="text/javascript">
                                 for(let i=0;i<1;i++){
                                    let k=document.getElementById('id_teamSize')
                                    console.log(k.value)
                                 myfunction(k);}
                                 function myfunction(k)
                                 {
                                    console.log(k)
                                  var l="div_id_userDetail"
                                  for(i=1 ;i<=3;i++){
                                   if(i<=k.value){
                                    document.getElementById(l+String(i)).style.display="block";
               // document.getElementById('id_userDetail'+String(i)).attributes["required"]="";
               //document.getElementById('id_userDetail'+String(i)).setAttribute('id_userDetail'+String(i),"required")
            }
            else{
               document.getElementById(l+String(i)).style.display="none";
               document.getElementById('id_userDetail'+String(i)).removeAttribute("required"); 
            }
            console.log(document.getElementById('id_userDetail'+String(i)).attributes);
         }
      }
      
      details="{{detail}}";
      if(details.length != 0)
      {
         window.top.top.location.href = "detail/"+details;
      }
   </script>
</body>
</html>

hackme/templates/hackme/detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Detail</title>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style>
	body
	{
		background-image: url("../static/images/bg.png");
		background-repeat: no-repeat;
		
	}
	
</style>
</head>
<body>
	<div class ="container">
		<br>
		<div class="container">
			<div class="row">
				<div class="col-md-9">
					<div class="panel panel-default">
						<div class="panel-body">
							<div class="row">
								<div class="col-md-4 text-center">
									<img class="img-circle avatar avatar-original" style="-webkit-user-select:none; 
									display:block; margin:auto;" src="http://robohash.org/sitsequiquia.png?size=120x120">
								</div>
								<div class="col-md-8">
									<div class="row">
										<div class="col-md-12">
											{% for i in teamName %}
											<h2 class="only-bottom-margin" style="color:orange;font-size:2.5em;">{{i.teamName}}</h2>
											<br>
										</div>
									</div>
									<div style="font-weight: bold; font-size: 20px; color: white;">
										<div class="row">
											<div class="col-md-15">
												
												<span class="text-muted ">Team Name:- </span>{{i.teamName}}<br>
												<span class="text-muted"></span><br>
												<span class="text-muted">Email Address:- </span>{{i.emailAddress}}<br>
												<span class="text-muted"></span><br>
												<span class="text-muted">Team Size:- </span>{{i.teamSize}}<br>

												<br>
												<br>
												<h5 style="color:orange;font-size: 1.5em;">Team Details</h5>
												{% if i.userDetail1|length > 0 %}
												<span class="text-muted"></span><br>
												<span class="text-muted">User 1:- </span>{{i.userDetail1}}<br>
												{% endif %}

												{% if i.userDetail2|length > 0 %}
												<span class="text-muted"></span><br>
												<span class="text-muted">User 2:- </span> {{i.userDetail2}}<br>
												{% endif %}

												{% if i.userDetail3|length > 0 %}
												<span class="text-muted"></span><br>										
												<span class="text-muted">User 3:- </span>{{i.userDetail3}}<br>
												{% endif %}

												{% if i.userDetail4|length > 0 %}
												<span class="text-muted"></span><br>
												<span class="text-muted">User 4:- </span>{{i.userDetail4}}
												{% endif %}

												<br>
												<br>
												<h5 style="color:orange;font-size:1.5em;">Project Details</h5>
												<span class="text-muted"></span><br>
												<span class="text-muted">Project Field:- </span>{{i.fieldProject}}<br>

												<span class="text-muted"></span><br>
												<span class="text-muted">Project Title:- </span>{{i.title}}<br>

												<span class="text-muted"></span><br>
												<span class="text-muted">Synopsis:- </span>{{i.synopsis}}<br>
												{% endfor %}
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<br>
	<script type="text/javascript">
		function startTimer() {
			alert("Your are successfully registered!! We are redirecting you to the main page!! All The Best!!")
			window.location.href="/";
		}
		setTimeout("startTimer()", 10000);
	</script>
</body>
</html>

hackme/templates/hackme/form.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head>
</SCRIPT>
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style type="text/css">
.loader {
	border: 16px solid #f3f3f3;
	border-radius: 50%;
	border-top: 16px solid blue;
	border-bottom: 16px solid blue;
	width: 120px;
	height: 120px;
	-webkit-animation: spin 2s linear infinite;
	animation: spin 2s linear infinite;
}
.container .btn {
	position: relative;
	top: 50%;
	left: 35%;
	border: none;
	color: black;
	padding: 15px 32px;
	text-align: center;
	text-decoration: none;
	display: inline-block;
	font-size: 16px;
	margin: 4px 2px;
	cursor: pointer;
}

.container .btn:hover {
	background-color: black;
	color: white;
}
</style>
<title>Register</title>
</head>
<body>
	<form method="POST" action="">
		<br>
		
		<div class="container-fluid">
			
			<div class="container">
				<b>
					{{form | crispy }}
					{% csrf_token %}
					<button class="btn">
						Register
					</button>
					
				</b>
				
			</div>
		</div>
	</form>

	<script type="text/javascript">
		
	</script>
</body>
</html>

hackme/templates/hackme/rform.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
<head>
</SCRIPT>
{% load static %}
<meta charset="utf-8">
<title>Register</title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<!-- Font-->
<link rel="stylesheet" type="text/css" href="static/css/nunito-font.css">
<!-- Main Style Css -->
<link rel="stylesheet" href="static/css/style.css"/>


</head>
<body class="form-v9">
	<div class="page-content">
		<div class="form-v9-content" style="background-image: url('static/images/form-v9.jpg')">
			<form class="form-detail" method="POST" action="">
				<div class="container-fluid">
					<b>
						{% csrf_token %}

						{% for non_field_error in form.non_field_errors %}
						<p class="help is-danger">{{ non_field_error }}</p>
						{% endfor %}

						
						<div class="form-row-total">
							<div class="form-row">
								<label for="{{ form.teamName.id_for_label }}" class="label">Team Name</label>
								{{ form.teamName }}
								{% for error in form.teamName.errors %}
								<p class="help is-danger">{{ error }}</p>
								{% endfor %}
							</div>
						</div>

						<div class="form-row-total">
							<div class="form-row">
								<label for="{{ form.emailAddress.id_for_label }}" class="label">Email Address</label>
								{{ form.emailAddress }}
								{% for error in field.errors %}
								<p class="help is-danger">{{ error }}</p>
								{% endfor %}
							</div>
						</div>

						<div class="form-row-total">
							<div class="form-row">
								<label for="{{ form.teamSize.id_for_label }}" class="label">Team Size</label>
								{{ form.teamSize }}
								{% for error in form.teamSize.errors %}
								<p class="help is-danger">{{ error }}</p>
								{% endfor %}
							</div>
						</div>


						<div class="form-row-total">
							<div class="form-row">
								<label for="{{ form.userDetail.id_for_label }}" class="form-control">User Details</label>
								{{ form.userDetail1 }}
								{% for error in form.userDetail1.errors %}
								<p class="help is-danger">{{ error }}</p>
								{% endfor %}
							</div>
						</div>

						<div class="form-row">
							<label for="{{ form.fieldProject.id_for_label }}" class="label">Project Field</label>
							{{ form.fieldProject }}
							{% for error in form.fieldProject.errors %}
							<p class="help is-danger">{{ error }}</p>
							{% endfor %}
						</div>
					</div>

					<div class="form-row-total">
						<div class="form-row">
							<label for="{{ form.title.id_for_label }}" class="label">Project Title</label>
							{{ form.title }}
							{% for error in form.title.errors %}
							<p class="help is-danger">{{ error }}</p>
							{% endfor %}
						</div>
					</div>

					<div class="form-row-total">
						<div class="form-row">
							<label for="{{ form.synopsis.id_for_label }}" class="label">Synopsis</label>
							{{ form.synopsis }}
							{% for error in form.synopsis.errors %}
							<p class="help is-danger">{{ error }}</p>
							{% endfor %}
						</div>
					</div>

				</b>
				<div class="form-row-last">
					<button class="btn">Register</button>
				</div>
			</div>
		</form>
	</div>
</div>
</body>
</html>